import type { Metadata } from 'next';
import { Montserrat as FontSans } from 'next/font/google';
import Footer from '../components/layouts/footer';
import Navbar from '../components/layouts/navbar';
import './globals.css';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
    title: 'CSTAM 1.0',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${fontSans.variable}`}>
                <Navbar />
                <main className='flex flex-col md:gap-32 gap-20 py-20'>
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
